;; DGO definition file for Awful Village level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("RCK.DGO"
 ("static-screen.o"
 "village1-part.o"
 "village1-part2.o"
 "village-obs.o"
 "beach-obs.o"
 "beach-part.o"
 "air-h.o"
 "air.o"
 "seagull.o"
 "lurkerworm.o"
 "lurkercrab.o"
 "lurkerpuppy.o"
 "twister.o"
 "jungle-obs.o"
 "jungle-part.o"
  ;; "rockpool-obs.o"
 "plat-ag.go"
  ;; "rockpool-ag.go"
 "lurkercrab-ag.go"
 "lurkerpuppy-ag.go"
 "lurkerworm-ag.go"
 "villa-starfish-ag.go"
 "seagull-ag.go"
 "ropebridge-52-ag.go"
 "rockpool.go"
 ))
